# fly.toml app configuration file generated for mahtava-hello-world-tekele on 2024-10-07T14:22:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mahtava-hello-world-tekele'
primary_region = 'arn'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
